name: "cachix"
on:
  push:
jobs:
  nixos-unstable:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sodiboo
        extraPullNames: niri
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build configurations and push to cachix
    #   run: nix-store --query --requisites $(nix-store --query --deriver $(nix build --print-out-paths .#__cached)) | cachix push niri
      run: nix build .#__cached